
#include <algorithm>
#include <array>
#include <cmath>
#include <ctime>
#include <fstream>
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtc/type_ptr.hpp>
#include <iostream>
#include <limits>
#include <string>
#include <type_traits>
#include <unordered_map>
#include <vector>
#include <xmmintrin.h>
#include <immintrin.h>
#include <emmintrin.h>
#include <chrono>
#include "../src/auxiliary_functions.hpp"
#include "../src/print_functions.hpp"
